navsat_transform_node:
  frequency: 10
  delay: 3
  magnetic_declination_radians: 0  # Adjust this based on your location
  yaw_offset: 0
  zero_altitude: true
  broadcast_utm_transform: true
  publish_filtered_gps: true