version: '3'

services:
  sfitc_ros-node:
    image: ros_indigo
    container_name: sfitc_ros-node
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://0.0.0.0:11311
      - ROS_IP=0.0.0.0
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /media/joseph/Development/DS:/lidar_data
      - ./sfitc/catkin_ws:/root/catkin_ws
    stdin_open: true
    tty: true
    command: /bin/bash

  sfitc_ros_cartographer:
    image: ros:noetic
    container_name: sfitc_ros_cartographer
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://0.0.0.0:11311
      - ROS_IP=0.0.0.0
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /media/joseph/Development/DS:/lidar_data
      - ./sfitc/catkin_ws:/root/catkin_ws
    stdin_open: true
    tty: true
    command: /bin/bash
