version: '3'

services:
  loam_velodyne:
    image: ros_indigo
    container_name: sfitc-ros-loam_velodyne
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://192.168.123.161:11311
      - ROS_IP=192.168.123.9
    volumes:
      - ./loam_velodyne/catkin_ws:/root/catkin_ws
    stdin_open: true
    tty: true
    command: /bin/bash

  zed:
    image: stereolabs/zed:3.8-runtime-cuda11.7-ubuntu20.04
    container_name: sfitc-zed
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw