version: '3'

services:
  vlp:
    image: sfitc-vlp
    container_name: sfitc-vlp
    network_mode: host
    # restart: always
    privileged: true
    environment:
      - ROS_MASTER_URI=http://0.0.0.0:11311
      - ROS_IP=0.0.0.0

  rtk:
    image: sfitc-rtk
    container_name: sfitc-rtk
    network_mode: host
    # restart: always
    privileged: true
    environment:
      - ROS_MASTER_URI=http://0.0.0.0:11311
      - ROS_IP=0.0.0.0
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ../RTK:/RTK
      - ./rtk/catkin_ws:/root/catkin_ws
    stdin_open: true
    tty: true

  ### Docker "run"
  # docker run -d --name sfitc-vlp -e ROS_MASTER_URI=http://192.168.123.161:11311 -e ROS_IP=192.168.123.13 --net host --restart always sfitc-vlp-arm64
  # docker run -it --name sfitc-vlp -e ROS_MASTER_URI=http://0.0.0.0:11311 -e ROS_IP=0.0.0.0 --net host sfitc-vlp
  # docker run -it --name sfitc-vlp -e ROS_MASTER_URI=http://0.0.0.0:11311 -e ROS_IP=0.0.0.0 --net host --restart always sfitc-vlp-arm64:device_ip
